// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQg5YpmUKRJt8wbebUxVYi9kmAk35YKU',
    appId: '1:909707662887:web:baf7c8788239946402e002',
    messagingSenderId: '909707662887',
    projectId: 'roommate-ce085',
    authDomain: 'roommate-ce085.firebaseapp.com',
    storageBucket: 'roommate-ce085.firebasestorage.app',
    measurementId: 'G-6TC6W7R76R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCja-bkvIOQ_J3nMOuXwC2ZHQrPMLrm-0U',
    appId: '1:909707662887:android:7a630deca2b73e4b02e002',
    messagingSenderId: '909707662887',
    projectId: 'roommate-ce085',
    storageBucket: 'roommate-ce085.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHD2EDGTODXTx8KKG7kfNDTNvuSUXWuwI',
    appId: '1:909707662887:ios:0564e07e6b47aadb02e002',
    messagingSenderId: '909707662887',
    projectId: 'roommate-ce085',
    storageBucket: 'roommate-ce085.firebasestorage.app',
    androidClientId: '909707662887-20r55ceq10oc92bradn9o6dp7dv44ouu.apps.googleusercontent.com',
    iosClientId: '909707662887-8kg5aidlop7iaq8qp01qpdf2ei4fhosd.apps.googleusercontent.com',
    iosBundleId: 'com.example.roommate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHD2EDGTODXTx8KKG7kfNDTNvuSUXWuwI',
    appId: '1:909707662887:ios:0564e07e6b47aadb02e002',
    messagingSenderId: '909707662887',
    projectId: 'roommate-ce085',
    storageBucket: 'roommate-ce085.firebasestorage.app',
    androidClientId: '909707662887-20r55ceq10oc92bradn9o6dp7dv44ouu.apps.googleusercontent.com',
    iosClientId: '909707662887-8kg5aidlop7iaq8qp01qpdf2ei4fhosd.apps.googleusercontent.com',
    iosBundleId: 'com.example.roommate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQg5YpmUKRJt8wbebUxVYi9kmAk35YKU',
    appId: '1:909707662887:web:3847cf394a8bb30802e002',
    messagingSenderId: '909707662887',
    projectId: 'roommate-ce085',
    authDomain: 'roommate-ce085.firebaseapp.com',
    storageBucket: 'roommate-ce085.firebasestorage.app',
    measurementId: 'G-YFK1DKYFM0',
  );
}
